print("initializing telescope")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>pg', function()
  builtin.live_grep({ search = vim.fn.input("Live Grep > ") })
end, { desc = 'Telescope live grep' })
